### ISSUE TITLE
Question about the calculation of yhat

### ISSUE THREAD

**Issue by Anery** [princeton-nlp/SimCSE#15]
Hi, I don't understand why we should use np.dot(xx, [1,2,3,4,5]) when calculating yhat. What is that for?

https://github.com/princeton-nlp/SimCSE/blob/6164c3571b4fb0b1a8b0947ad75294e5386a563a/SentEval/senteval/tools/relatedness.py#L83-L101

**Comment by gaotianyu1350** [comment]
Hi, 

It's because the SICK-R task rates sentence pairs between 1 and 5. Also, this code is actually not used in our evaluation. It is the additional regressor implementation from [SentEval](/content/drive/MyDrive/courses/COS524/Final Project/models/bert_model/tf_model.preproc) (see Appendix B: additional regressor).

**Comment by Anery** [comment]
I know what's the dataset like, I just don't understand the meaning of inner product in line 86..
Maybe I should check it in SentEval. Thank you
