### ISSUE TITLE
about fixed 0.1 dropout rate

### ISSUE THREAD

**Issue by Chen-Hao-fc** [princeton-nlp/SimCSE#36]
Simcse is a amazing work! Appreciate your hard work.
I have a question. how you implemented the dropout **fixed 0.1** operation in the code?

**Comment by gaotianyu1350** [comment]
Hi,

We don't have the option in the current public repository (since it's an ablation model), but you can implement it easily by yourself. First make sure that you feed a single-sentence dataset to the model, and in the model code, instead of forwarding the input twice, you just forward it once and use the same representation for the second representation (`z2 = z1`).

**Comment by Chen-Hao-fc** [comment]
thanks
