### ISSUE TITLE
Questions on Experiment Section

### ISSUE THREAD

**Issue by jin8** [princeton-nlp/SimCSE#54]
First of all thank you for sharing your paper and code on Constrastive learning for sentence embeddings.
I have few questions regarding the paper!

1. In the paper, the result of unsupervised SimCSE in tables 1-5 seem to be trained with wiki 1m data.  It's kind of unclear in tables 6-7, which dataset are being used to fine-tune in unsupervised setting.  Or do they use nli dataset as supervised setting, sts-b train set, or wiki 1m data as prior tables?  

2. In transfer tasks section, it mentions about BERT-flow/whitening. I was not able to see the result in Table 7. Do you have plans adding them?

3. In transfer tasks section, I do understand on the concept of flattening the embedding space by reducing the eigenvalue. Have you conduct additional experiment to support your argument that "good uniformity of representations does not lead to better embedding for transfer learning"?  Or is this argument based on the result in table 7? 

Any feedback or comments are appreciated!
Thank you,
Jin

**Comment by gaotianyu1350** [comment]
Hi,

1. For all unsupervised results, we use Wikipedia (1M) data. For supervised results, we take NLI datasets. Sorry that the naming causes some confusion, but none of the experiments use STS-B training set for fine-tuning. In standard sentence embedding setting, STS-B is only used for testing. 

2. We didn't add them because the two papers didn't report the numbers and also by our reproduction the results are similar to vanilla BERT/RoBERTa (in some cases, even worse).

3. The argument just comes from intuition and you can say that Table 7 to some extent supports the argument.

**Comment by jin8** [comment]
Thank you! My confusion has been cleared up :)
