### ISSUE TITLE
Plan to release the pretrained model on SNLI+MNLI entailment + hard negative 

### ISSUE THREAD

**Issue by LeCongThuong** [princeton-nlp/SimCSE#7]
Thank you for sharing your great work!
Do you have any plan for releasing pretrained model on SNLI+MNLI entailment + hard negative?
Do you any plan for doing experiments about training on  (SNLI+MNLI + STS training) and evaluate result on STS test?

**Comment by gaotianyu1350** [comment]
Hi,

We have already released SNLI+MNLI entailment + hard negative models. See our readme and all checkpoints starting with `sup-simcse-` are trained on SNLI+MNLI.

Since we assume a zero-shot setting on STS (i.e., we never use STS training data in SimCSE), we don't have plans for further fine-tuning the model on STS training set. However, feel free to do so by using our checkpoints.

**Comment by LeCongThuong** [comment]
Thank you for answering!
