### ISSUE TITLE
SimCSE for Masked Language Modelling

### ISSUE THREAD

**Issue by tanay2001** [princeton-nlp/SimCSE#76]
Thanks for providing such well documented code<br>
I was trying out the new models on masked language modelling tasks any idea how I should go about it since the saved checkpoints don't see to be compatible with `AutoModelForMaskedLM`

**Comment by gaotianyu1350** [comment]
Hi,

Since we don't tune the masked LM head in our task, you can simply take the masked LM head parameters from the corresponding pre-trained model (e.g., bert-base-uncased or roberta-large). Note that since the parameter of the model is changed, it might need further tuning with MLM data for it to work properly.
